return {
	BackgroundColor = require(script.Color.BackgroundColor),
	BorderRadius = require(script.Borders.BorderRadius),
	Center = require(script.Position.Center),
	Font = require(script.Typography.Font),
	Height = require(script.Size.Height),
	Invisible = require(script.Effects.Invisible),
	Italic = require(script.Typography.Italic),
	JustifyX = require(script.Layout.JustifyX),
	JustifyY = require(script.Layout.JustifyY),
	Lowercase = require(script.Typography.Lowercase),
	Object = require(script.Position.Object),
	Opacity = require(script.Effects.Opacity),
	PaddingX = require(script.Layout.PaddingX),
	PaddingY = require(script.Layout.PaddingY),
	Ring = require(script.Effects.Ring),
	SpaceX = require(script.Layout.SpaceX),
	SpaceY = require(script.Layout.SpaceY),
	Text = require(script.Typography.Text),
	TranslateX = require(script.Position.TranslateX),
	TranslateY = require(script.Position.TranslateY),
	Truncate = require(script.Typography.Truncate),
	Uppercase = require(script.Typography.Uppercase),
	Visible = require(script.Effects.Visible),
	Width = require(script.Size.Width),
}
