return {
	Box = {
		BackgroundColor = true,
		BorderRadius = true,
		Center = true,
		Height = true,
		Invisible = true,
		JustifyX = true,
		JustifyY = true,
		Object = true,
		Opacity = true,
		PaddingX = true,
		PaddingY = true,
		Ring = true,
		SpaceX = true,
		SpaceY = true,
		TranslateX = true,
		TranslateY = true,
		Visible = true,
		Width = true,
	},
	Text = {
		BackgroundColor = true,
		BorderRadius = true,
		Center = true,
		Font = true,
		Height = true,
		Invisible = true,
		Italic = true,
		JustifyX = true,
		JustifyY = true,
		Lowercase = true,
		Object = true,
		Opacity = true,
		PaddingX = true,
		PaddingY = true,
		Ring = true,
		SpaceX = true,
		SpaceY = true,
		Text = true,
		TranslateX = true,
		TranslateY = true,
		Truncate = true,
		Uppercase = true,
		Visible = true,
		Width = true,
	},
}
